framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'support-atypikhouse@example.com'
        headers:
            From: 'support-atypikhouse@example.com'
       