framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'contact.atypik-house@f2i-dev20-wd-al-ma-fa.fr'
        headers:
            From: 'contact.atypik-house@f2i-dev20-wd-al-ma-fa.fr'
       