controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

home:
    path: /
    controller: App\Controller\HomeController::index

auth:
    path: /api/users/authentication
    methods: ["POST"]

swagger:
    path: /docs
    controller: api_platform.swagger.action.ui