# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

    password: 'test'
    images_directory: '%kernel.project_dir%/public/images'
    stripe_public_key: pk_test_51LJG4GLpq4M4X10NpEssXhrxV6ugbBOm8pXDVzcxhz9Dlzc17un8No755ghMk7R0kTgyBsQAIq8fwX9PPBFNQMIQ00PrZeLY7O
    stripe_secret_key: sk_test_51LJG4GLpq4M4X10NCi2E7Mcc70SmSKMCWMdpTPxPHnT1iinbaxAlxvZBjUJL7zB1gHXsOeBA6qaH6nPImkC5a5mM00QM10AuTU
    domain: 'http://localhost:8000'
    payment:
        currency: EUR
        decimal: true

services:
    
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%images_directory%/uploads'

    App\OpenApi\JwtDecorator:
            decorates: 'api_platform.openapi.factory'
            arguments: ['@.inner']
    